In [1]:
import pandas as pd
from pandas_datareader import data

In [31]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]
p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

In [32]:
p.transpose()

Date                  2009-12-31    2010-01-04    2010-01-05    2010-01-06  \
Attributes Symbols
High       AAPL     3.047857e+01  3.064286e+01  3.079857e+01  3.074714e+01
           AMZN     1.372800e+02  1.366100e+02  1.354800e+02  1.347300e+02
           GOOG     3.106793e+02  3.127210e+02  3.118914e+02  3.109078e+02
           IBM      1.328500e+02  1.329700e+02  1.318500e+02  1.314900e+02
           MSFT     3.099000e+01  3.110000e+01  3.110000e+01  3.108000e+01
Low        AAPL     3.008000e+01  3.034000e+01  3.046428e+01  3.010714e+01
           AMZN     1.345200e+02  1.331400e+02  1.318100e+02  1.316500e+02
           GOOG     3.079868e+02  3.101031e+02  3.087618e+02  3.012209e+02
           IBM      1.307500e+02  1.308500e+02  1.301000e+02  1.298100e+02
           MSFT     3.048000e+01  3.059000e+01  3.064000e+01  3.052000e+01
Open       AAPL     3.044714e+01  3.049000e+01  3.065714e+01  3.062571e+01
           AMZN     1.370900e+02  1.362500e+02  1.334300e+02  1.346000e+02
           GOOG     3.103564e+02  3.114493e+02  3.115636e+02  3.109078e+02
           IBM      1.324100e+02  1.311800e+02  1.316800e+02  1.306800e+02
           MSFT     3.098000e+01  3.062000e+01  3.085000e+01  3.088000e+01
Close      AAPL     3.010429e+01  3.057286e+01  3.062571e+01  3.013857e+01
           AMZN     1.345200e+02  1.339000e+02  1.346900e+02  1.322500e+02
           GOOG     3.079868e+02  3.113500e+02  3.099789e+02  3.021647e+02
           IBM      1.309000e+02  1.324500e+02  1.308500e+02  1.300000e+02
           MSFT     3.048000e+01  3.095000e+01  3.096000e+01  3.077000e+01
Volume     AAPL     8.810270e+07  1.234324e+08  1.504762e+08  1.380400e+08
           AMZN     4.523000e+06  7.599900e+06  8.851900e+06  7.178800e+06
           GOOG     2.455400e+06  3.937800e+06  6.048500e+06  8.009000e+06
           IBM      4.223400e+06  6.155300e+06  6.841400e+06  5.605300e+06
           MSFT     3.192970e+07  3.840910e+07  4.974960e+07  5.818240e+07
Adj Close  AAPL     1.999662e+01  2.030787e+01  2.034298e+01  2.001940e+01
           AMZN     1.345200e+02  1.339000e+02  1.346900e+02  1.322500e+02
           GOOG     3.079868e+02  3.113500e+02  3.099789e+02  3.021647e+02
           IBM      9.813728e+01  9.929935e+01  9.809979e+01  9.746253e+01
           MSFT     2.415258e+01  2.452502e+01  2.453294e+01  2.438238e+01

Date                  2010-01-07    2010-01-08    2010-01-11    2010-01-12  \
Attributes Symbols
High       AAPL     3.028572e+01  3.028572e+01  3.042857e+01  2.996714e+01
           AMZN     1.323200e+02  1.336800e+02  1.328000e+02  1.298200e+02
           GOOG     3.030291e+02  2.996759e+02  3.002770e+02  2.971473e+02
           IBM      1.302500e+02  1.309200e+02  1.310600e+02  1.313300e+02
           MSFT     3.070000e+01  3.088000e+01  3.076000e+01  3.040000e+01
Low        AAPL     2.986429e+01  2.986572e+01  2.977857e+01  2.948857e+01
           AMZN     1.288000e+02  1.290300e+02  1.292100e+02  1.265500e+02
           GOOG     2.944102e+02  2.926516e+02  2.951006e+02  2.921002e+02
           IBM      1.289100e+02  1.290500e+02  1.286700e+02  1.290000e+02
           MSFT     3.019000e+01  3.024000e+01  3.012000e+01  2.991000e+01
Open       AAPL     3.025000e+01  3.004286e+01  3.040000e+01  2.988428e+01
           AMZN     1.320100e+02  1.305600e+02  1.326200e+02  1.289900e+02
           GOOG     3.027310e+02  2.940872e+02  3.002770e+02  2.968940e+02
           IBM      1.298700e+02  1.290700e+02  1.310600e+02  1.290300e+02
           MSFT     3.063000e+01  3.028000e+01  3.071000e+01  3.015000e+01
Close      AAPL     3.008286e+01  3.028286e+01  3.001571e+01  2.967429e+01
           AMZN     1.300000e+02  1.335200e+02  1.303100e+02  1.273500e+02
           GOOG     2.951305e+02  2.990649e+02  2.986128e+02  2.933322e+02
           IBM      1.295500e+02  1.308500e+02  1.294800e+02  1.305100e+02
           MSFT     3.045000e+01  3.066000e+01  3.027000e+01  3.007000e+01
Volume     AAPL     1.192828e+08  1.119027e+08  1.155574e+08  1.486149e+08
           AMZN     1.103020e+07  9.830500e+06  8.779400e+06  9.096300e+06
           GOOG     1.291200e+07  9.509900e+06  1.451960e+07  9.769600e+06
           IBM      5.840600e+06  4.197200e+06  5.730400e+06  8.081500e+06
           MSFT     5.055970e+07  5.119740e+07  6.875470e+07  6.591210e+07
Adj Close  AAPL     1.998239e+01  2.011524e+01  1.993779e+01  1.971099e+01
           AMZN     1.300000e+02  1.335200e+02  1.303100e+02  1.273500e+02
           GOOG     2.951305e+02  2.990649e+02  2.986128e+02  2.933322e+02
           IBM      9.712516e+01  9.809979e+01  9.707269e+01  9.784487e+01
           MSFT     2.412881e+01  2.429521e+01  2.398618e+01  2.382769e+01

Date                  2010-01-13    2010-01-14      ...         2016-12-16  \
Attributes Symbols                                  ...
High       AAPL     3.013286e+01  3.006571e+01      ...       1.165000e+02
           AMZN     1.297100e+02  1.303800e+02      ...       7.651300e+02
           GOOG     2.922889e+02  2.951801e+02      ...       8.008560e+02
           IBM      1.311200e+02  1.327100e+02      ...       1.691100e+02
           MSFT     3.052000e+01  3.110000e+01      ...       6.295000e+01
Low        AAPL     2.915714e+01  2.986000e+01      ...       1.156500e+02
           AMZN     1.257500e+02  1.264000e+02      ...       7.540000e+02
           GOOG     2.850957e+02  2.895219e+02      ...       7.902900e+02
           IBM      1.291600e+02  1.299100e+02      ...       1.660600e+02
           MSFT     3.001000e+01  3.026000e+01      ...       6.212000e+01
Open       AAPL     2.969571e+01  3.001571e+01      ...       1.164700e+02
           AMZN     1.279000e+02  1.291400e+02      ...       7.650000e+02
           GOOG     2.863824e+02  2.900634e+02      ...       8.004000e+02
           IBM      1.303900e+02  1.305500e+02      ...       1.689700e+02
           MSFT     3.026000e+01  3.031000e+01      ...       6.295000e+01
Close      AAPL     3.009286e+01  2.991857e+01      ...       1.159700e+02
           AMZN     1.291100e+02  1.273500e+02      ...       7.577700e+02
           GOOG     2.916481e+02  2.930192e+02      ...       7.908000e+02
           IBM      1.302300e+02  1.323100e+02      ...       1.667300e+02
           MSFT     3.035000e+01  3.096000e+01      ...       6.230000e+01
Volume     AAPL     1.514730e+08  1.082235e+08      ...       4.435110e+07
           AMZN     1.072320e+07  9.774900e+06      ...       4.828700e+06
           GOOG     1.307760e+07  8.535300e+06      ...       2.428300e+06
           IBM      6.455400e+06  7.111800e+06      ...       6.679200e+06
           MSFT     5.186350e+07  6.322810e+07      ...       4.220470e+07
Adj Close  AAPL     1.998903e+01  1.987326e+01      ...       1.115367e+02
           AMZN     1.291100e+02  1.273500e+02      ...       7.577700e+02
           GOOG     2.916481e+02  2.930192e+02      ...       7.908000e+02
           IBM      9.763496e+01  9.919439e+01      ...       1.500084e+02
           MSFT     2.404957e+01  2.453294e+01      ...       5.942760e+01

Date                  2016-12-19    2016-12-20    2016-12-21    2016-12-22  \
Attributes Symbols
High       AAPL     1.173800e+02  1.175000e+02  1.174000e+02  1.165100e+02
           AMZN     7.705000e+02  7.743900e+02  7.712200e+02  7.712100e+02
           GOOG     7.976600e+02  7.986500e+02  7.966760e+02  7.933200e+02
           IBM      1.672600e+02  1.682500e+02  1.679400e+02  1.682300e+02
           MSFT     6.377000e+01  6.380000e+01  6.370000e+01  6.410000e+01
Low        AAPL     1.157500e+02  1.166800e+02  1.167800e+02  1.156400e+02
           AMZN     7.561600e+02  7.677100e+02  7.657000e+02  7.630200e+02
           GOOG     7.862700e+02  7.932700e+02  7.871000e+02  7.885800e+02
           IBM      1.660000e+02  1.664500e+02  1.652500e+02  1.665800e+02
           MSFT     6.242000e+01  6.303000e+01  6.312000e+01  6.341000e+01
Open       AAPL     1.158000e+02  1.167400e+02  1.168000e+02  1.163500e+02
           AMZN     7.588900e+02  7.686500e+02  7.700000e+02  7.681200e+02
           GOOG     7.902200e+02  7.967600e+02  7.958400e+02  7.923600e+02
           IBM      1.668300e+02  1.674900e+02  1.662500e+02  1.673600e+02
           MSFT     6.256000e+01  6.369000e+01  6.343000e+01  6.384000e+01
Close      AAPL     1.166400e+02  1.169500e+02  1.170600e+02  1.162900e+02
           AMZN     7.660000e+02  7.712200e+02  7.706000e+02  7.663400e+02
           GOOG     7.942000e+02  7.964200e+02  7.945600e+02  7.912600e+02
           IBM      1.666800e+02  1.676000e+02  1.673300e+02  1.670600e+02
           MSFT     6.362000e+01  6.354000e+01  6.354000e+01  6.355000e+01
Volume     AAPL     2.777940e+07  2.142500e+07  2.378320e+07  2.608590e+07
           AMZN     3.113200e+06  2.703600e+06  2.044600e+06  2.543600e+06
           GOOG     1.232100e+06  9.510000e+05  1.211300e+06  9.722000e+05
           IBM      2.955900e+06  2.174600e+06  3.575700e+06  2.802600e+06
           MSFT     3.433820e+07  2.602840e+07  1.709630e+07  2.217660e+07
Adj Close  AAPL     1.121811e+02  1.124792e+02  1.125850e+02  1.118445e+02
           AMZN     7.660000e+02  7.712200e+02  7.706000e+02  7.663400e+02
           GOOG     7.942000e+02  7.964200e+02  7.945600e+02  7.912600e+02
           IBM      1.499634e+02  1.507912e+02  1.505482e+02  1.503053e+02
           MSFT     6.068674e+01  6.061043e+01  6.061043e+01  6.061997e+01

Date                  2016-12-23    2016-12-27    2016-12-28    2016-12-29  \
Attributes Symbols
High       AAPL     1.165200e+02  1.178000e+02  1.180200e+02  1.171100e+02
           AMZN     7.665000e+02  7.746500e+02  7.800000e+02  7.734000e+02
           GOOG     7.927400e+02  7.978600e+02  7.942300e+02  7.859300e+02
           IBM      1.674900e+02  1.679800e+02  1.677400e+02  1.669900e+02
           MSFT     6.354000e+01  6.407000e+01  6.340000e+01  6.320000e+01
Low        AAPL     1.155900e+02  1.164900e+02  1.162000e+02  1.164000e+02
           AMZN     7.579900e+02  7.612000e+02  7.705000e+02  7.608500e+02
           GOOG     7.872800e+02  7.876570e+02  7.832000e+02  7.789200e+02
           IBM      1.664500e+02  1.668500e+02  1.660000e+02  1.660000e+02
           MSFT     6.280000e+01  6.321000e+01  6.283000e+01  6.273000e+01
Open       AAPL     1.155900e+02  1.165200e+02  1.175200e+02  1.164500e+02
           AMZN     7.645500e+02  7.634000e+02  7.762500e+02  7.724000e+02
           GOOG     7.909000e+02  7.906800e+02  7.937000e+02  7.833300e+02
           IBM      1.670000e+02  1.669800e+02  1.672900e+02  1.660200e+02
           MSFT     6.345000e+01  6.321000e+01  6.340000e+01  6.286000e+01
Close      AAPL     1.165200e+02  1.172600e+02  1.167600e+02  1.167300e+02
           AMZN     7.605900e+02  7.714000e+02  7.721300e+02  7.651500e+02
           GOOG     7.899100e+02  7.915500e+02  7.850500e+02  7.827900e+02
           IBM      1.667100e+02  1.671400e+02  1.661900e+02  1.666000e+02
           MSFT     6.324000e+01  6.328000e+01  6.299000e+01  6.290000e+01
Volume     AAPL     1.424950e+07  1.829690e+07  2.090590e+07  1.503950e+07
           AMZN     1.976900e+06  2.638700e+06  3.301000e+06  3.153500e+06
           GOOG     6.234000e+05  7.891000e+05  1.153800e+06  7.422000e+05
           IBM      1.699200e+06  1.397500e+06  1.757500e+06  1.594000e+06
           MSFT     1.239800e+07  1.176320e+07  1.465330e+07  1.018160e+07
Adj Close  AAPL     1.120657e+02  1.127774e+02  1.122965e+02  1.122676e+02
           AMZN     7.605900e+02  7.714000e+02  7.721300e+02  7.651500e+02
           GOOG     7.899100e+02  7.915500e+02  7.850500e+02  7.827900e+02
           IBM      1.499904e+02  1.503773e+02  1.495225e+02  1.498914e+02
           MSFT     6.032426e+01  6.036242e+01  6.008578e+01  5.999994e+01

Date                  2016-12-30
Attributes Symbols
High       AAPL     1.172000e+02
           AMZN     7.674000e+02
           GOOG     7.827800e+02
           IBM      1.667000e+02
           MSFT     6.299000e+01
Low        AAPL     1.154300e+02
           AMZN     7.482800e+02
           GOOG     7.704100e+02
           IBM      1.655000e+02
           MSFT     6.203000e+01
Open       AAPL     1.166500e+02
           AMZN     7.664700e+02
           GOOG     7.827500e+02
           IBM      1.664400e+02
           MSFT     6.296000e+01
Close      AAPL     1.158200e+02
           AMZN     7.498700e+02
           GOOG     7.718200e+02
           IBM      1.659900e+02
           MSFT     6.214000e+01
Volume     AAPL     3.058630e+07
           AMZN     4.139400e+06
           GOOG     1.770000e+06
           IBM      2.952800e+06
           MSFT     2.557990e+07
Adj Close  AAPL     1.113924e+02
           AMZN     7.498700e+02
           GOOG     7.718200e+02
           IBM      1.493426e+02
           MSFT     5.927497e+01

[30 rows x 1763 columns]

In [33]:
type(p)

pandas.core.frame.DataFrame

## The Axes of the Panel

In [7]:
# companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

# p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

# p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

Dimensions tells 'no of data frames'; major_axis tells 'no of rows'; minor_axis tells 'no of columns'

In [9]:
p.items

<bound method DataFrame.iteritems of Attributes        High                                                 \
Symbols           AAPL        AMZN        GOOG         IBM       MSFT
Date
2009-12-31   30.478571  137.279999  310.679321  132.850006  30.990000
2010-01-04   30.642857  136.610001  312.721039  132.970001  31.100000
2010-01-05   30.798571  135.479996  311.891449  131.850006  31.100000
2010-01-06   30.747143  134.729996  310.907837  131.490005  31.080000
2010-01-07   30.285715  132.320007  303.029083  130.250000  30.700001
2010-01-08   30.285715  133.679993  299.675903  130.919998  30.879999
2010-01-11   30.428572  132.800003  300.276978  131.059998  30.760000
2010-01-12   29.967142  129.820007  297.147339  131.330002  30.400000
2010-01-13   30.132856  129.710007  292.288940  131.119995  30.520000
2010-01-14   30.065714  130.380005  295.180145  132.710007  31.100000
2010-01-15   30.228571  129.649994  294.862213  132.889999  31.240000
2010-01-19   30.741428  128.000000  293.302338  134.250000  31.240000
2010-01-20   30.792856  129.199997  291.096710  131.149994  30.940001
2010-01-21   30.472857  128.149994  291.513977  130.690002  30.719999
2010-01-22   29.642857  127.669998  283.456390  128.889999  30.200001
2010-01-25   29.242857  122.279999  273.163330  126.889999  29.660000
2010-01-26   30.530001  122.980003  273.024231  127.750000  29.850000
2010-01-27   30.082857  123.330002  272.055542  126.959999  29.820000
2010-01-28   29.357143  127.199997  271.732635  127.040001  29.870001
2010-01-29   28.885714  131.850006  268.747070  125.000000  29.920000
2010-02-01   28.000000  124.860001  266.173798  124.949997  28.480000
2010-02-02   28.045713  118.980003  265.751556  125.809998  28.500000
2010-02-03   28.600000  119.610001  269.298462  126.070000  28.790001
2010-02-04   28.338572  120.330002  267.261719  125.440002  28.500000
2010-02-05   28.000000  117.650002  265.026245  123.720001  28.280001
2010-02-08   28.268572  121.000000  269.248810  123.220001  28.080000
2010-02-09   28.214285  119.089996  269.015320  124.199997  28.340000
2010-02-10   28.085714  118.610001  267.157410  123.650002  28.240000
2010-02-11   28.535715  120.419998  268.498688  124.199997  28.400000
2010-02-12   28.805714  119.940002  266.839478  124.050003  28.059999
...                ...         ...         ...         ...        ...
2016-11-17  110.349998  757.500000  772.700012  159.929993  60.950001
2016-11-18  110.540001  767.739990  775.000000  160.720001  61.139999
2016-11-21  111.989998  780.349976  769.700012  163.000000  60.970001
2016-11-22  112.419998  792.400024  776.960022  163.000000  61.259998
2016-11-23  111.510002  781.750000  768.283020  162.380005  61.099998
2016-11-25  111.870003  786.750000  765.000000  163.190002  60.529999
2016-11-28  112.470001  777.000000  779.530029  164.660004  61.020000
2016-11-29  112.029999  769.890015  778.500000  164.410004  61.410000
2016-11-30  112.199997  768.090027  772.989990  163.800003  61.180000
2016-12-01  110.940002  753.369995  759.849976  162.199997  60.150002
2016-12-02  110.089996  748.489990  754.000000  160.289993  59.470001
2016-12-05  110.029999  761.489990  763.900024  161.149994  60.590000
2016-12-06  110.360001  768.239990  768.830017  160.789993  60.459999
2016-12-07  111.190002  770.419983  771.359985  165.179993  61.380001
2016-12-08  112.430000  773.789978  778.179993  166.000000  61.580002
2016-12-09  114.699997  770.250000  789.429993  166.720001  61.990002
2016-12-12  115.000000  766.890015  791.250000  166.789993  62.299999
2016-12-13  115.919998  782.460022  804.380005  169.949997  63.419998
2016-12-14  116.199997  780.859985  804.000000  169.889999  63.450001
2016-12-15  116.730003  769.099976  803.000000  169.850006  63.150002
2016-12-16  116.500000  765.130005  800.856018  169.110001  62.950001
2016-12-19  117.379997  770.500000  797.659973  167.259995  63.770000
2016-12-20  117.500000  774.390015  798.650024  168.250000  63.799999
2016-12-21  117.400002  771.219971  796.676025  167.940002  63.700001
2016-12-22  116.510002  771.210022  793.320007  168.229996  64.099998
2016-12-23  116.519997  766.500000  792.739990  167.490005  63.540001
2016-12-27  117.800003  774.650024  797.859985  167.979996  64.070000
2016-12-28  118.019997  780.000000  794.229980  167.740005  63.400002
2016-12-29  117.110001  773.400024  785.929993  166.990005  63.200001
2016-12-30  117.199997  767.400024  782.780029  166.699997  62.990002

Attributes         Low                                                 \
Symbols           AAPL        AMZN        GOOG         IBM       MSFT
Date
2009-12-31   30.080000  134.520004  307.986847  130.750000  30.480000
2010-01-04   30.340000  133.139999  310.103088  130.850006  30.590000
2010-01-05   30.464285  131.809998  308.761810  130.100006  30.639999
2010-01-06   30.107143  131.649994  301.220856  129.809998  30.520000
2010-01-07   29.864286  128.800003  294.410156  128.910004  30.190001
2010-01-08   29.865715  129.029999  292.651581  129.050003  30.240000
2010-01-11   29.778572  129.210007  295.100647  128.669998  30.120001
2010-01-12   29.488571  126.550003  292.100159  129.000000  29.910000
2010-01-13   29.157143  125.750000  285.095734  129.160004  30.010000
2010-01-14   29.860001  126.400002  289.521942  129.910004  30.260000
2010-01-15   29.410000  127.059998  287.152344  131.089996  30.709999
2010-01-19   29.605715  124.330002  286.283020  131.559998  30.680000
2010-01-20   29.928572  125.080002  285.786224  128.949997  30.309999
2010-01-21   29.601429  125.000000  284.276062  128.059998  30.000000
2010-01-22   28.165714  120.760002  265.701874  125.370003  28.840000
2010-01-25   28.598572  118.120003  266.024780  125.709999  29.100000
2010-01-26   28.940001  119.059998  266.412231  125.410004  29.090000
2010-01-27   28.504286  118.800003  265.925415  125.040001  29.020000
2010-01-28   28.385714  122.800003  263.585632  123.050003  28.889999
2010-01-29   27.178572  124.139999  261.106750  121.900002  27.660000
2010-02-01   27.328571  113.820000  263.436584  122.779999  27.920000
2010-02-02   27.625713  114.400002  262.100281  123.949997  28.139999
2010-02-03   27.774286  116.559998  262.408295  125.070000  28.120001
2010-02-04   27.367144  115.739998  261.081909  122.900002  27.809999
2010-02-05   27.264286  114.099998  259.541931  121.830002  27.570000
2010-02-08   27.714285  116.559998  264.047638  121.739998  27.570000
2010-02-09   27.821428  117.000000  265.806183  122.459999  27.750000
2010-02-10   27.751429  116.000000  262.140045  122.209999  27.840000
2010-02-11   27.722857  116.500000  263.039185  122.059998  27.700001
2010-02-12   27.928572  117.500000  263.535950  121.610001  27.580000
...                ...         ...         ...         ...        ...
2016-11-17  108.830002  748.000000  764.229980  158.850006  59.970001
2016-11-18  109.660004  757.640015  760.000000  159.210007  60.299999
2016-11-21  110.010002  765.109985  760.599976  160.369995  60.419998
2016-11-22  111.400002  781.000000  767.000000  161.949997  60.810001
2016-11-23  110.330002  773.119995  755.250000  161.360001  60.250000
2016-11-25  110.949997  777.900024  760.520020  161.830002  60.130001
2016-11-28  111.389999  764.239990  759.799988  162.699997  60.209999
2016-11-29  110.070000  761.320007  768.239990  163.029999  60.520000
2016-11-30  110.269997  750.250000  754.830017  162.210007  60.220001
2016-12-01  109.029999  738.030029  737.025024  158.300003  58.939999
2016-12-02  108.849998  736.700012  743.099976  158.410004  58.799999
2016-12-05  108.250000  742.000000  752.900024  159.589996  59.560001
2016-12-06  109.190002  757.250000  757.340027  158.929993  59.799999
2016-12-07  109.160004  755.820007  755.799988  160.389999  59.799999
2016-12-08  110.599998  765.190002  767.229980  164.220001  60.840000
2016-12-09  112.309998  765.340027  779.020996  164.600006  61.130001
2016-12-12  112.489998  757.200012  784.354980  165.070007  61.720001
2016-12-13  113.750000  762.000000  793.340027  165.679993  62.240002
2016-12-14  114.980003  762.809998  794.010010  167.449997  62.529999
2016-12-15  115.230003  760.309998  792.919983  167.779999  62.299999
2016-12-16  115.650002  754.000000  790.289978  166.059998  62.119999
2016-12-19  115.750000  756.159973  786.270020  166.000000  62.419998
2016-12-20  116.680000  767.710022  793.270020  166.449997  63.029999
2016-12-21  116.779999  765.700012  787.099976  165.250000  63.119999
2016-12-22  115.639999  763.020020  788.580017  166.580002  63.410000
2016-12-23  115.589996  757.989990  787.280029  166.449997  62.799999
2016-12-27  116.489998  761.200012  787.656982  166.850006  63.209999
2016-12-28  116.199997  770.500000  783.200012  166.000000  62.830002
2016-12-29  116.400002  760.849976  778.919983  166.000000  62.730000
2016-12-30  115.430000  748.280029  770.409973  165.500000  62.029999

Attributes    ...           Volume                                      \
Symbols       ...             AAPL        AMZN        GOOG         IBM
Date          ...
2009-12-31    ...       88102700.0   4523000.0   2455400.0   4223400.0
2010-01-04    ...      123432400.0   7599900.0   3937800.0   6155300.0
2010-01-05    ...      150476200.0   8851900.0   6048500.0   6841400.0
2010-01-06    ...      138040000.0   7178800.0   8009000.0   5605300.0
2010-01-07    ...      119282800.0  11030200.0  12912000.0   5840600.0
2010-01-08    ...      111902700.0   9830500.0   9509900.0   4197200.0
2010-01-11    ...      115557400.0   8779400.0  14519600.0   5730400.0
2010-01-12    ...      148614900.0   9096300.0   9769600.0   8081500.0
2010-01-13    ...      151473000.0  10723200.0  13077600.0   6455400.0
2010-01-14    ...      108223500.0   9774900.0   8535300.0   7111800.0
2010-01-15    ...      148516900.0  15376500.0  10939600.0   8494400.0
2010-01-19    ...      182501900.0   8892600.0   8689500.0  13916200.0
2010-01-20    ...      153038200.0   9074700.0   6543600.0  15197500.0
2010-01-21    ...      152038600.0   9970600.0  12697400.0   9608600.0
2010-01-22    ...      220441900.0  11568900.0  13689200.0  10088600.0
2010-01-25    ...      266424900.0  12023900.0   8897200.0   5738500.0
2010-01-26    ...      466777500.0   9559000.0   8767600.0   7135300.0
2010-01-27    ...      430642100.0  14765300.0   7980200.0   8719200.0
2010-01-28    ...      293375600.0  27293100.0   6500100.0   9622200.0
2010-01-29    ...      311488100.0  29471300.0   8334700.0  11571200.0
2010-02-01    ...      187469100.0  37774400.0   4530800.0   7242900.0
2010-02-02    ...      174585600.0  23079700.0   8245600.0   5899900.0
2010-02-03    ...      153832000.0  12405900.0   6037000.0   4177100.0
2010-02-04    ...      189413000.0  12784000.0   6799200.0   9126900.0
2010-02-05    ...      212576700.0  11024800.0   6353000.0   8617000.0
2010-02-08    ...      119567700.0   9890200.0   5423500.0   5718500.0
2010-02-09    ...      158221700.0   9223000.0   5675700.0   6044500.0
2010-02-10    ...       92590400.0   6233200.0   5383700.0   5219100.0
2010-02-11    ...      137586400.0   8343500.0   4851300.0   5089000.0
2010-02-12    ...      163867200.0   8073500.0   4589000.0   8017700.0
...           ...              ...         ...         ...         ...
2016-11-17    ...       27632000.0   3690100.0   1304000.0   2261200.0
2016-11-18    ...       28428900.0   4373400.0   1547100.0   2981600.0
2016-11-21    ...       29264600.0   4614600.0   1330600.0   4637100.0
2016-11-22    ...       25965500.0   5311300.0   1593100.0   2770800.0
2016-11-23    ...       27426400.0   3522500.0   1477400.0   2252700.0
2016-11-25    ...       11475900.0   1837100.0    587400.0   1605300.0
2016-11-28    ...       27194000.0   4438800.0   2188200.0   4449400.0
2016-11-29    ...       28528800.0   3272300.0   1616600.0   3148200.0
2016-11-30    ...       36162300.0   4625900.0   2392900.0   4397800.0
2016-12-01    ...       37086900.0   4666000.0   3017900.0   4635700.0
2016-12-02    ...       26528000.0   3561300.0   1452500.0   2740900.0
2016-12-05    ...       34324500.0   4314700.0   1394200.0   3447100.0
2016-12-06    ...       26195500.0   3794700.0   1690700.0   2859000.0
2016-12-07    ...       29998700.0   3684900.0   1761000.0   4435100.0
2016-12-08    ...       27068300.0   3189600.0   1488100.0   3266400.0
2016-12-09    ...       34402600.0   2470900.0   1821900.0   3146900.0
2016-12-12    ...       26374400.0   2963900.0   2104100.0   3392300.0
2016-12-13    ...       43733800.0   5285300.0   2145200.0   5932300.0
2016-12-14    ...       34031800.0   5454800.0   1704200.0   4124200.0
2016-12-15    ...       46524500.0   3801900.0   1626500.0   3388600.0
2016-12-16    ...       44351100.0   4828700.0   2428300.0   6679200.0
2016-12-19    ...       27779400.0   3113200.0   1232100.0   2955900.0
2016-12-20    ...       21425000.0   2703600.0    951000.0   2174600.0
2016-12-21    ...       23783200.0   2044600.0   1211300.0   3575700.0
2016-12-22    ...       26085900.0   2543600.0    972200.0   2802600.0
2016-12-23    ...       14249500.0   1976900.0    623400.0   1699200.0
2016-12-27    ...       18296900.0   2638700.0    789100.0   1397500.0
2016-12-28    ...       20905900.0   3301000.0   1153800.0   1757500.0
2016-12-29    ...       15039500.0   3153500.0    742200.0   1594000.0
2016-12-30    ...       30586300.0   4139400.0   1770000.0   2952800.0

Attributes                Adj Close                                      \
Symbols            MSFT        AAPL        AMZN        GOOG         IBM
Date
2009-12-31   31929700.0   19.996618  134.520004  307.986847   98.137283
2010-01-04   38409100.0   20.307869  133.899994  311.349976   99.299347
2010-01-05   49749600.0   20.342979  134.690002  309.978882   98.099792
2010-01-06   58182400.0   20.019398  132.250000  302.164703   97.462532
2010-01-07   50559700.0   19.982389  130.000000  295.130463   97.125160
2010-01-08   51197400.0   20.115240  133.520004  299.064880   98.099792
2010-01-11   68754700.0   19.937790  130.309998  298.612823   97.072685
2010-01-12   65912100.0   19.710993  127.349998  293.332153   97.844872
2010-01-13   51863500.0   19.989031  129.110001  291.648102   97.634964
2010-01-14   63228100.0   19.873259  127.349998  293.019196   99.194389
2010-01-15   79913200.0   19.541140  127.139999  288.126007   98.797028
2010-01-19   46575700.0   20.405605  127.610001  291.911407  100.566330
2010-01-20   54849500.0   20.091518  125.779999  288.329681   97.649979
2010-01-21   73086700.0   19.744209  126.620003  289.606384   96.712860
2010-01-22  102004600.0   18.764919  121.430000  273.227905   94.088844
2010-01-25   63373000.0   19.269749  120.309998  268.255249   94.553688
2010-01-26   66639900.0   19.542088  119.480003  269.457428   94.276276
2010-01-27   63949500.0   19.726181  122.750000  269.298462   94.711105
2010-01-28  117513700.0   18.911057  126.029999  265.418701   92.776848
2010-01-29  193888500.0   18.224987  125.410004  263.257751   91.757233
2010-02-01   85931100.0   18.478348  118.870003  264.787811   93.466576
2010-02-02   54413700.0   18.585581  118.120003  263.843964   94.111336
2010-02-03   61397900.0   18.905357  119.099998  268.662598   94.208817
2010-02-04   77850000.0   18.224039  115.940002  261.687958   92.214569
2010-02-05   80960100.0   18.547623  117.389999  263.928406   92.604401
2010-02-08   52820600.0   18.420462  116.830002  265.011353   91.783577
2010-02-09   59195800.0   18.616892  118.029999  266.486755   92.785126
2010-02-10   48591300.0   18.515354  117.360001  265.498199   92.483902
2010-02-11   65993700.0   18.852224  120.089996  266.466888   93.176750
2010-02-12   81117200.0   19.014488  119.660004  264.837494   93.380051
...                 ...         ...         ...         ...         ...
2016-11-17   32132700.0  105.746819  756.400024  771.229980  143.773407
2016-11-18   27686300.0  105.852631  760.159973  760.539978  144.304260
2016-11-21   19652600.0  107.458794  780.000000  769.200012  146.445526
2016-11-22   23206700.0  107.526115  785.330017  768.270020  146.355576
2016-11-23   21847200.0  106.977898  780.119995  760.989990  145.734787
2016-11-25    8409600.0  107.516495  780.369995  761.679993  146.778442
2016-11-28   20732600.0  107.304909  766.770020  768.239990  148.020004
2016-11-29   22366700.0  107.199104  762.520020  770.840027  147.129318
2016-11-30   34655400.0  106.295036  750.570007  758.039978  145.950714
2016-12-01   34542100.0  105.304413  743.650024  747.919983  143.791412
2016-12-02   25515700.0  105.698738  740.340027  750.500000  143.971344
2016-12-05   23552700.0  104.938942  759.359985  762.520020  143.809418
2016-12-06   19907000.0  105.746819  764.719971  759.109985  144.268250
2016-12-07   30809000.0  106.785538  770.419983  771.190002  148.262955
2016-12-08   21220800.0  107.833870  767.330017  776.419983  148.775772
2016-12-09   27349400.0  109.593918  768.659973  789.289978  149.819458
2016-12-12   20198100.0  108.968758  760.119995  789.270020  148.901749
2016-12-13   35718900.0  110.786522  774.340027  796.099976  151.411926
2016-12-14   30352700.0  110.786522  768.820007  797.070007  151.609863
2016-12-15   27669900.0  111.392426  761.000000  797.849976  151.169022
2016-12-16   42204700.0  111.536713  757.770020  790.799988  150.008392
2016-12-19   34338200.0  112.181091  766.000000  794.200012  149.963379
2016-12-20   26028400.0  112.479225  771.219971  796.419983  150.791168
2016-12-21   17096300.0  112.585030  770.599976  794.559998  150.548203
2016-12-22   22176600.0  111.844475  766.340027  791.260010  150.305267
2016-12-23   12398000.0  112.065674  760.590027  789.909973  149.990402
2016-12-27   11763200.0  112.777390  771.400024  791.549988  150.377258
2016-12-28   14653300.0  112.296501  772.130005  785.049988  149.522537
2016-12-29   10181600.0  112.267647  765.150024  782.789978  149.891418
2016-12-30   25579900.0  111.392426  749.869995  771.820007  149.342606

Attributes
Symbols          MSFT
Date
2009-12-31  24.152580
2010-01-04  24.525019
2010-01-05  24.532942
2010-01-06  24.382378
2010-01-07  24.128809
2010-01-08  24.295214
2010-01-11  23.986179
2010-01-12  23.827694
2010-01-13  24.049570
2010-01-14  24.532942
2010-01-15  24.453693
2010-01-19  24.643881
2010-01-20  24.239746
2010-01-21  23.780155
2010-01-22  22.948128
2010-01-25  23.233395
2010-01-26  23.376024
2010-01-27  23.510740
2010-01-28  23.106604
2010-01-29  22.330048
2010-02-01  22.512297
2010-02-02  22.551926
2010-02-03  22.686628
2010-02-04  22.060629
2010-02-05  22.203266
2010-02-08  21.965540
2010-02-09  22.195339
2010-02-10  22.179491
2010-02-11  22.282507
2010-02-12  22.131947
...               ...
2016-11-17  57.844143
2016-11-18  57.567513
2016-11-21  58.053997
2016-11-22  58.302006
2016-11-23  57.615211
2016-11-25  57.739204
2016-11-28  57.815521
2016-11-29  58.273388
2016-11-30  57.481655
2016-12-01  56.470524
2016-12-02  56.518223
2016-12-05  57.443508
2016-12-06  57.185951
2016-12-07  58.540485
2016-12-08  58.197079
2016-12-09  59.112816
2016-12-12  59.303596
2016-12-13  60.076248
2016-12-14  59.790081
2016-12-15  59.694695
2016-12-16  59.427597
2016-12-19  60.686745
2016-12-20  60.610432
2016-12-21  60.610432
2016-12-22  60.619972
2016-12-23  60.324265
2016-12-27  60.362419
2016-12-28  60.085785
2016-12-29  59.999939
2016-12-30  59.274975

[1763 rows x 30 columns]>

In [13]:
p.index

DatetimeIndex(['2009-12-31', '2010-01-04', '2010-01-05', '2010-01-06',
               '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
               '2010-01-13', '2010-01-14',
               ...
               '2016-12-16', '2016-12-19', '2016-12-20', '2016-12-21',
               '2016-12-22', '2016-12-23', '2016-12-27', '2016-12-28',
               '2016-12-29', '2016-12-30'],
              dtype='datetime64[ns]', name='Date', length=1763, freq=None)

In [15]:
p.columns

MultiIndex(levels=[['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close'], ['AAPL', 'AMZN', 'GOOG', 'IBM', 'MSFT']],
           labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
           names=['Attributes', 'Symbols'])

In [16]:
p.axes

[DatetimeIndex(['2009-12-31', '2010-01-04', '2010-01-05', '2010-01-06',
                '2010-01-07', '2010-01-08', '2010-01-11', '2010-01-12',
                '2010-01-13', '2010-01-14',
                ...
                '2016-12-16', '2016-12-19', '2016-12-20', '2016-12-21',
                '2016-12-22', '2016-12-23', '2016-12-27', '2016-12-28',
                '2016-12-29', '2016-12-30'],
               dtype='datetime64[ns]', name='Date', length=1763, freq=None),
 MultiIndex(levels=[['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close'], ['AAPL', 'AMZN', 'GOOG', 'IBM', 'MSFT']],
            labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
            names=['Attributes', 'Symbols'])]

In [25]:
p.index.names
p.columns.names
p.columns.unique

<bound method MultiIndex.unique of MultiIndex(levels=[['High', 'Low', 'Open', 'Close', 'Volume', 'Adj Close'], ['AAPL', 'AMZN', 'GOOG', 'IBM', 'MSFT']],
           labels=[[0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 3, 3, 3, 3, 3, 4, 4, 4, 4, 4, 5, 5, 5, 5, 5], [0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4, 0, 1, 2, 3, 4]],
           names=['Attributes', 'Symbols'])>

## Panel Attributes

In [31]:
# companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

# p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

# p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [26]:
p.axes
p.items
# p.major_axis
# p.minor_axis

<bound method DataFrame.iteritems of Attributes        High                                                 \
Symbols           AAPL        AMZN        GOOG         IBM       MSFT
Date
2009-12-31   30.478571  137.279999  310.679321  132.850006  30.990000
2010-01-04   30.642857  136.610001  312.721039  132.970001  31.100000
2010-01-05   30.798571  135.479996  311.891449  131.850006  31.100000
2010-01-06   30.747143  134.729996  310.907837  131.490005  31.080000
2010-01-07   30.285715  132.320007  303.029083  130.250000  30.700001
2010-01-08   30.285715  133.679993  299.675903  130.919998  30.879999
2010-01-11   30.428572  132.800003  300.276978  131.059998  30.760000
2010-01-12   29.967142  129.820007  297.147339  131.330002  30.400000
2010-01-13   30.132856  129.710007  292.288940  131.119995  30.520000
2010-01-14   30.065714  130.380005  295.180145  132.710007  31.100000
2010-01-15   30.228571  129.649994  294.862213  132.889999  31.240000
2010-01-19   30.741428  128.000000  293.302338  134.250000  31.240000
2010-01-20   30.792856  129.199997  291.096710  131.149994  30.940001
2010-01-21   30.472857  128.149994  291.513977  130.690002  30.719999
2010-01-22   29.642857  127.669998  283.456390  128.889999  30.200001
2010-01-25   29.242857  122.279999  273.163330  126.889999  29.660000
2010-01-26   30.530001  122.980003  273.024231  127.750000  29.850000
2010-01-27   30.082857  123.330002  272.055542  126.959999  29.820000
2010-01-28   29.357143  127.199997  271.732635  127.040001  29.870001
2010-01-29   28.885714  131.850006  268.747070  125.000000  29.920000
2010-02-01   28.000000  124.860001  266.173798  124.949997  28.480000
2010-02-02   28.045713  118.980003  265.751556  125.809998  28.500000
2010-02-03   28.600000  119.610001  269.298462  126.070000  28.790001
2010-02-04   28.338572  120.330002  267.261719  125.440002  28.500000
2010-02-05   28.000000  117.650002  265.026245  123.720001  28.280001
2010-02-08   28.268572  121.000000  269.248810  123.220001  28.080000
2010-02-09   28.214285  119.089996  269.015320  124.199997  28.340000
2010-02-10   28.085714  118.610001  267.157410  123.650002  28.240000
2010-02-11   28.535715  120.419998  268.498688  124.199997  28.400000
2010-02-12   28.805714  119.940002  266.839478  124.050003  28.059999
...                ...         ...         ...         ...        ...
2016-11-17  110.349998  757.500000  772.700012  159.929993  60.950001
2016-11-18  110.540001  767.739990  775.000000  160.720001  61.139999
2016-11-21  111.989998  780.349976  769.700012  163.000000  60.970001
2016-11-22  112.419998  792.400024  776.960022  163.000000  61.259998
2016-11-23  111.510002  781.750000  768.283020  162.380005  61.099998
2016-11-25  111.870003  786.750000  765.000000  163.190002  60.529999
2016-11-28  112.470001  777.000000  779.530029  164.660004  61.020000
2016-11-29  112.029999  769.890015  778.500000  164.410004  61.410000
2016-11-30  112.199997  768.090027  772.989990  163.800003  61.180000
2016-12-01  110.940002  753.369995  759.849976  162.199997  60.150002
2016-12-02  110.089996  748.489990  754.000000  160.289993  59.470001
2016-12-05  110.029999  761.489990  763.900024  161.149994  60.590000
2016-12-06  110.360001  768.239990  768.830017  160.789993  60.459999
2016-12-07  111.190002  770.419983  771.359985  165.179993  61.380001
2016-12-08  112.430000  773.789978  778.179993  166.000000  61.580002
2016-12-09  114.699997  770.250000  789.429993  166.720001  61.990002
2016-12-12  115.000000  766.890015  791.250000  166.789993  62.299999
2016-12-13  115.919998  782.460022  804.380005  169.949997  63.419998
2016-12-14  116.199997  780.859985  804.000000  169.889999  63.450001
2016-12-15  116.730003  769.099976  803.000000  169.850006  63.150002
2016-12-16  116.500000  765.130005  800.856018  169.110001  62.950001
2016-12-19  117.379997  770.500000  797.659973  167.259995  63.770000
2016-12-20  117.500000  774.390015  798.650024  168.250000  63.799999
2016-12-21  117.400002  771.219971  796.676025  167.940002  63.700001
2016-12-22  116.510002  771.210022  793.320007  168.229996  64.099998
2016-12-23  116.519997  766.500000  792.739990  167.490005  63.540001
2016-12-27  117.800003  774.650024  797.859985  167.979996  64.070000
2016-12-28  118.019997  780.000000  794.229980  167.740005  63.400002
2016-12-29  117.110001  773.400024  785.929993  166.990005  63.200001
2016-12-30  117.199997  767.400024  782.780029  166.699997  62.990002

Attributes         Low                                                 \
Symbols           AAPL        AMZN        GOOG         IBM       MSFT
Date
2009-12-31   30.080000  134.520004  307.986847  130.750000  30.480000
2010-01-04   30.340000  133.139999  310.103088  130.850006  30.590000
2010-01-05   30.464285  131.809998  308.761810  130.100006  30.639999
2010-01-06   30.107143  131.649994  301.220856  129.809998  30.520000
2010-01-07   29.864286  128.800003  294.410156  128.910004  30.190001
2010-01-08   29.865715  129.029999  292.651581  129.050003  30.240000
2010-01-11   29.778572  129.210007  295.100647  128.669998  30.120001
2010-01-12   29.488571  126.550003  292.100159  129.000000  29.910000
2010-01-13   29.157143  125.750000  285.095734  129.160004  30.010000
2010-01-14   29.860001  126.400002  289.521942  129.910004  30.260000
2010-01-15   29.410000  127.059998  287.152344  131.089996  30.709999
2010-01-19   29.605715  124.330002  286.283020  131.559998  30.680000
2010-01-20   29.928572  125.080002  285.786224  128.949997  30.309999
2010-01-21   29.601429  125.000000  284.276062  128.059998  30.000000
2010-01-22   28.165714  120.760002  265.701874  125.370003  28.840000
2010-01-25   28.598572  118.120003  266.024780  125.709999  29.100000
2010-01-26   28.940001  119.059998  266.412231  125.410004  29.090000
2010-01-27   28.504286  118.800003  265.925415  125.040001  29.020000
2010-01-28   28.385714  122.800003  263.585632  123.050003  28.889999
2010-01-29   27.178572  124.139999  261.106750  121.900002  27.660000
2010-02-01   27.328571  113.820000  263.436584  122.779999  27.920000
2010-02-02   27.625713  114.400002  262.100281  123.949997  28.139999
2010-02-03   27.774286  116.559998  262.408295  125.070000  28.120001
2010-02-04   27.367144  115.739998  261.081909  122.900002  27.809999
2010-02-05   27.264286  114.099998  259.541931  121.830002  27.570000
2010-02-08   27.714285  116.559998  264.047638  121.739998  27.570000
2010-02-09   27.821428  117.000000  265.806183  122.459999  27.750000
2010-02-10   27.751429  116.000000  262.140045  122.209999  27.840000
2010-02-11   27.722857  116.500000  263.039185  122.059998  27.700001
2010-02-12   27.928572  117.500000  263.535950  121.610001  27.580000
...                ...         ...         ...         ...        ...
2016-11-17  108.830002  748.000000  764.229980  158.850006  59.970001
2016-11-18  109.660004  757.640015  760.000000  159.210007  60.299999
2016-11-21  110.010002  765.109985  760.599976  160.369995  60.419998
2016-11-22  111.400002  781.000000  767.000000  161.949997  60.810001
2016-11-23  110.330002  773.119995  755.250000  161.360001  60.250000
2016-11-25  110.949997  777.900024  760.520020  161.830002  60.130001
2016-11-28  111.389999  764.239990  759.799988  162.699997  60.209999
2016-11-29  110.070000  761.320007  768.239990  163.029999  60.520000
2016-11-30  110.269997  750.250000  754.830017  162.210007  60.220001
2016-12-01  109.029999  738.030029  737.025024  158.300003  58.939999
2016-12-02  108.849998  736.700012  743.099976  158.410004  58.799999
2016-12-05  108.250000  742.000000  752.900024  159.589996  59.560001
2016-12-06  109.190002  757.250000  757.340027  158.929993  59.799999
2016-12-07  109.160004  755.820007  755.799988  160.389999  59.799999
2016-12-08  110.599998  765.190002  767.229980  164.220001  60.840000
2016-12-09  112.309998  765.340027  779.020996  164.600006  61.130001
2016-12-12  112.489998  757.200012  784.354980  165.070007  61.720001
2016-12-13  113.750000  762.000000  793.340027  165.679993  62.240002
2016-12-14  114.980003  762.809998  794.010010  167.449997  62.529999
2016-12-15  115.230003  760.309998  792.919983  167.779999  62.299999
2016-12-16  115.650002  754.000000  790.289978  166.059998  62.119999
2016-12-19  115.750000  756.159973  786.270020  166.000000  62.419998
2016-12-20  116.680000  767.710022  793.270020  166.449997  63.029999
2016-12-21  116.779999  765.700012  787.099976  165.250000  63.119999
2016-12-22  115.639999  763.020020  788.580017  166.580002  63.410000
2016-12-23  115.589996  757.989990  787.280029  166.449997  62.799999
2016-12-27  116.489998  761.200012  787.656982  166.850006  63.209999
2016-12-28  116.199997  770.500000  783.200012  166.000000  62.830002
2016-12-29  116.400002  760.849976  778.919983  166.000000  62.730000
2016-12-30  115.430000  748.280029  770.409973  165.500000  62.029999

Attributes    ...           Volume                                      \
Symbols       ...             AAPL        AMZN        GOOG         IBM
Date          ...
2009-12-31    ...       88102700.0   4523000.0   2455400.0   4223400.0
2010-01-04    ...      123432400.0   7599900.0   3937800.0   6155300.0
2010-01-05    ...      150476200.0   8851900.0   6048500.0   6841400.0
2010-01-06    ...      138040000.0   7178800.0   8009000.0   5605300.0
2010-01-07    ...      119282800.0  11030200.0  12912000.0   5840600.0
2010-01-08    ...      111902700.0   9830500.0   9509900.0   4197200.0
2010-01-11    ...      115557400.0   8779400.0  14519600.0   5730400.0
2010-01-12    ...      148614900.0   9096300.0   9769600.0   8081500.0
2010-01-13    ...      151473000.0  10723200.0  13077600.0   6455400.0
2010-01-14    ...      108223500.0   9774900.0   8535300.0   7111800.0
2010-01-15    ...      148516900.0  15376500.0  10939600.0   8494400.0
2010-01-19    ...      182501900.0   8892600.0   8689500.0  13916200.0
2010-01-20    ...      153038200.0   9074700.0   6543600.0  15197500.0
2010-01-21    ...      152038600.0   9970600.0  12697400.0   9608600.0
2010-01-22    ...      220441900.0  11568900.0  13689200.0  10088600.0
2010-01-25    ...      266424900.0  12023900.0   8897200.0   5738500.0
2010-01-26    ...      466777500.0   9559000.0   8767600.0   7135300.0
2010-01-27    ...      430642100.0  14765300.0   7980200.0   8719200.0
2010-01-28    ...      293375600.0  27293100.0   6500100.0   9622200.0
2010-01-29    ...      311488100.0  29471300.0   8334700.0  11571200.0
2010-02-01    ...      187469100.0  37774400.0   4530800.0   7242900.0
2010-02-02    ...      174585600.0  23079700.0   8245600.0   5899900.0
2010-02-03    ...      153832000.0  12405900.0   6037000.0   4177100.0
2010-02-04    ...      189413000.0  12784000.0   6799200.0   9126900.0
2010-02-05    ...      212576700.0  11024800.0   6353000.0   8617000.0
2010-02-08    ...      119567700.0   9890200.0   5423500.0   5718500.0
2010-02-09    ...      158221700.0   9223000.0   5675700.0   6044500.0
2010-02-10    ...       92590400.0   6233200.0   5383700.0   5219100.0
2010-02-11    ...      137586400.0   8343500.0   4851300.0   5089000.0
2010-02-12    ...      163867200.0   8073500.0   4589000.0   8017700.0
...           ...              ...         ...         ...         ...
2016-11-17    ...       27632000.0   3690100.0   1304000.0   2261200.0
2016-11-18    ...       28428900.0   4373400.0   1547100.0   2981600.0
2016-11-21    ...       29264600.0   4614600.0   1330600.0   4637100.0
2016-11-22    ...       25965500.0   5311300.0   1593100.0   2770800.0
2016-11-23    ...       27426400.0   3522500.0   1477400.0   2252700.0
2016-11-25    ...       11475900.0   1837100.0    587400.0   1605300.0
2016-11-28    ...       27194000.0   4438800.0   2188200.0   4449400.0
2016-11-29    ...       28528800.0   3272300.0   1616600.0   3148200.0
2016-11-30    ...       36162300.0   4625900.0   2392900.0   4397800.0
2016-12-01    ...       37086900.0   4666000.0   3017900.0   4635700.0
2016-12-02    ...       26528000.0   3561300.0   1452500.0   2740900.0
2016-12-05    ...       34324500.0   4314700.0   1394200.0   3447100.0
2016-12-06    ...       26195500.0   3794700.0   1690700.0   2859000.0
2016-12-07    ...       29998700.0   3684900.0   1761000.0   4435100.0
2016-12-08    ...       27068300.0   3189600.0   1488100.0   3266400.0
2016-12-09    ...       34402600.0   2470900.0   1821900.0   3146900.0
2016-12-12    ...       26374400.0   2963900.0   2104100.0   3392300.0
2016-12-13    ...       43733800.0   5285300.0   2145200.0   5932300.0
2016-12-14    ...       34031800.0   5454800.0   1704200.0   4124200.0
2016-12-15    ...       46524500.0   3801900.0   1626500.0   3388600.0
2016-12-16    ...       44351100.0   4828700.0   2428300.0   6679200.0
2016-12-19    ...       27779400.0   3113200.0   1232100.0   2955900.0
2016-12-20    ...       21425000.0   2703600.0    951000.0   2174600.0
2016-12-21    ...       23783200.0   2044600.0   1211300.0   3575700.0
2016-12-22    ...       26085900.0   2543600.0    972200.0   2802600.0
2016-12-23    ...       14249500.0   1976900.0    623400.0   1699200.0
2016-12-27    ...       18296900.0   2638700.0    789100.0   1397500.0
2016-12-28    ...       20905900.0   3301000.0   1153800.0   1757500.0
2016-12-29    ...       15039500.0   3153500.0    742200.0   1594000.0
2016-12-30    ...       30586300.0   4139400.0   1770000.0   2952800.0

Attributes                Adj Close                                      \
Symbols            MSFT        AAPL        AMZN        GOOG         IBM
Date
2009-12-31   31929700.0   19.996618  134.520004  307.986847   98.137283
2010-01-04   38409100.0   20.307869  133.899994  311.349976   99.299347
2010-01-05   49749600.0   20.342979  134.690002  309.978882   98.099792
2010-01-06   58182400.0   20.019398  132.250000  302.164703   97.462532
2010-01-07   50559700.0   19.982389  130.000000  295.130463   97.125160
2010-01-08   51197400.0   20.115240  133.520004  299.064880   98.099792
2010-01-11   68754700.0   19.937790  130.309998  298.612823   97.072685
2010-01-12   65912100.0   19.710993  127.349998  293.332153   97.844872
2010-01-13   51863500.0   19.989031  129.110001  291.648102   97.634964
2010-01-14   63228100.0   19.873259  127.349998  293.019196   99.194389
2010-01-15   79913200.0   19.541140  127.139999  288.126007   98.797028
2010-01-19   46575700.0   20.405605  127.610001  291.911407  100.566330
2010-01-20   54849500.0   20.091518  125.779999  288.329681   97.649979
2010-01-21   73086700.0   19.744209  126.620003  289.606384   96.712860
2010-01-22  102004600.0   18.764919  121.430000  273.227905   94.088844
2010-01-25   63373000.0   19.269749  120.309998  268.255249   94.553688
2010-01-26   66639900.0   19.542088  119.480003  269.457428   94.276276
2010-01-27   63949500.0   19.726181  122.750000  269.298462   94.711105
2010-01-28  117513700.0   18.911057  126.029999  265.418701   92.776848
2010-01-29  193888500.0   18.224987  125.410004  263.257751   91.757233
2010-02-01   85931100.0   18.478348  118.870003  264.787811   93.466576
2010-02-02   54413700.0   18.585581  118.120003  263.843964   94.111336
2010-02-03   61397900.0   18.905357  119.099998  268.662598   94.208817
2010-02-04   77850000.0   18.224039  115.940002  261.687958   92.214569
2010-02-05   80960100.0   18.547623  117.389999  263.928406   92.604401
2010-02-08   52820600.0   18.420462  116.830002  265.011353   91.783577
2010-02-09   59195800.0   18.616892  118.029999  266.486755   92.785126
2010-02-10   48591300.0   18.515354  117.360001  265.498199   92.483902
2010-02-11   65993700.0   18.852224  120.089996  266.466888   93.176750
2010-02-12   81117200.0   19.014488  119.660004  264.837494   93.380051
...                 ...         ...         ...         ...         ...
2016-11-17   32132700.0  105.746819  756.400024  771.229980  143.773407
2016-11-18   27686300.0  105.852631  760.159973  760.539978  144.304260
2016-11-21   19652600.0  107.458794  780.000000  769.200012  146.445526
2016-11-22   23206700.0  107.526115  785.330017  768.270020  146.355576
2016-11-23   21847200.0  106.977898  780.119995  760.989990  145.734787
2016-11-25    8409600.0  107.516495  780.369995  761.679993  146.778442
2016-11-28   20732600.0  107.304909  766.770020  768.239990  148.020004
2016-11-29   22366700.0  107.199104  762.520020  770.840027  147.129318
2016-11-30   34655400.0  106.295036  750.570007  758.039978  145.950714
2016-12-01   34542100.0  105.304413  743.650024  747.919983  143.791412
2016-12-02   25515700.0  105.698738  740.340027  750.500000  143.971344
2016-12-05   23552700.0  104.938942  759.359985  762.520020  143.809418
2016-12-06   19907000.0  105.746819  764.719971  759.109985  144.268250
2016-12-07   30809000.0  106.785538  770.419983  771.190002  148.262955
2016-12-08   21220800.0  107.833870  767.330017  776.419983  148.775772
2016-12-09   27349400.0  109.593918  768.659973  789.289978  149.819458
2016-12-12   20198100.0  108.968758  760.119995  789.270020  148.901749
2016-12-13   35718900.0  110.786522  774.340027  796.099976  151.411926
2016-12-14   30352700.0  110.786522  768.820007  797.070007  151.609863
2016-12-15   27669900.0  111.392426  761.000000  797.849976  151.169022
2016-12-16   42204700.0  111.536713  757.770020  790.799988  150.008392
2016-12-19   34338200.0  112.181091  766.000000  794.200012  149.963379
2016-12-20   26028400.0  112.479225  771.219971  796.419983  150.791168
2016-12-21   17096300.0  112.585030  770.599976  794.559998  150.548203
2016-12-22   22176600.0  111.844475  766.340027  791.260010  150.305267
2016-12-23   12398000.0  112.065674  760.590027  789.909973  149.990402
2016-12-27   11763200.0  112.777390  771.400024  791.549988  150.377258
2016-12-28   14653300.0  112.296501  772.130005  785.049988  149.522537
2016-12-29   10181600.0  112.267647  765.150024  782.789978  149.891418
2016-12-30   25579900.0  111.392426  749.869995  771.820007  149.342606

Attributes
Symbols          MSFT
Date
2009-12-31  24.152580
2010-01-04  24.525019
2010-01-05  24.532942
2010-01-06  24.382378
2010-01-07  24.128809
2010-01-08  24.295214
2010-01-11  23.986179
2010-01-12  23.827694
2010-01-13  24.049570
2010-01-14  24.532942
2010-01-15  24.453693
2010-01-19  24.643881
2010-01-20  24.239746
2010-01-21  23.780155
2010-01-22  22.948128
2010-01-25  23.233395
2010-01-26  23.376024
2010-01-27  23.510740
2010-01-28  23.106604
2010-01-29  22.330048
2010-02-01  22.512297
2010-02-02  22.551926
2010-02-03  22.686628
2010-02-04  22.060629
2010-02-05  22.203266
2010-02-08  21.965540
2010-02-09  22.195339
2010-02-10  22.179491
2010-02-11  22.282507
2010-02-12  22.131947
...               ...
2016-11-17  57.844143
2016-11-18  57.567513
2016-11-21  58.053997
2016-11-22  58.302006
2016-11-23  57.615211
2016-11-25  57.739204
2016-11-28  57.815521
2016-11-29  58.273388
2016-11-30  57.481655
2016-12-01  56.470524
2016-12-02  56.518223
2016-12-05  57.443508
2016-12-06  57.185951
2016-12-07  58.540485
2016-12-08  58.197079
2016-12-09  59.112816
2016-12-12  59.303596
2016-12-13  60.076248
2016-12-14  59.790081
2016-12-15  59.694695
2016-12-16  59.427597
2016-12-19  60.686745
2016-12-20  60.610432
2016-12-21  60.610432
2016-12-22  60.619972
2016-12-23  60.324265
2016-12-27  60.362419
2016-12-28  60.085785
2016-12-29  59.999939
2016-12-30  59.274975

[1763 rows x 30 columns]>

In [27]:
p.ndim

2

In [28]:
p.dtypes

Attributes  Symbols
High        AAPL       float64
            AMZN       float64
            GOOG       float64
            IBM        float64
            MSFT       float64
Low         AAPL       float64
            AMZN       float64
            GOOG       float64
            IBM        float64
            MSFT       float64
Open        AAPL       float64
            AMZN       float64
            GOOG       float64
            IBM        float64
            MSFT       float64
Close       AAPL       float64
            AMZN       float64
            GOOG       float64
            IBM        float64
            MSFT       float64
Volume      AAPL       float64
            AMZN       float64
            GOOG       float64
            IBM        float64
            MSFT       float64
Adj Close   AAPL       float64
            AMZN       float64
            GOOG       float64
            IBM        float64
            MSFT       float64
dtype: object

In [29]:
p.shape

(1763, 30)

In [39]:
p.size

42200

In [40]:
5 * 1688 * 5

42200

## Extracting `DataFrames` from a `Panel` Using Bracket Notation

In [42]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [43]:
p.items

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [46]:
p["Volume"]

                   AAPL        AMZN       GOOG         MSFT        YHOO
Date
2010-01-04  123432050.0   7600543.0        NaN   38414185.0  16588957.0
2010-01-05  150476004.0   8856456.0        NaN   49758862.0  11718126.0
2010-01-06  138039594.0   7180977.0        NaN   58182332.0  16421960.0
2010-01-07  119282324.0  11030124.0        NaN   50564285.0  31816301.0
2010-01-08  111969081.0   9833829.0        NaN   51201289.0  15471074.0
2010-01-11  115557365.0   8786668.0        NaN   68754648.0  16185267.0
2010-01-12  148614774.0   9098190.0        NaN   65913228.0  15674461.0
2010-01-13  151472335.0  10727856.0        NaN   51863463.0  16961731.0
2010-01-14  108288411.0   9788435.0        NaN   63244767.0  16717061.0
2010-01-15  148584065.0  15382763.0        NaN   79915648.0  18415868.0
2010-01-19  182501620.0   8900116.0        NaN   46582886.0  15182984.0
2010-01-20  153037892.0   9081533.0        NaN   54857712.0  14421141.0
2010-01-21  152038565.0   9976146.0        NaN   73086701.0  21860505.0
2010-01-22  220441872.0  11577818.0        NaN  102004573.0  25135493.0
2010-01-25  266424802.0  12031053.0        NaN   63381173.0  19683693.0
2010-01-26  466777486.0   9567607.0        NaN   66647676.0  43979302.0
2010-01-27  430642030.0  14765273.0        NaN   63949492.0  41700911.0
2010-01-28  293375376.0  27293062.0        NaN  117513692.0  30159437.0
2010-01-29  311487785.0  29478976.0        NaN  193888424.0  39667312.0
2010-02-01  187468421.0  37774317.0        NaN   85931099.0  29865661.0
2010-02-02  174585313.0  23084986.0        NaN   54413654.0  27556624.0
2010-02-03  153831769.0  12409012.0        NaN   61397848.0  24730564.0
2010-02-04  189412762.0  12783912.0        NaN   77849968.0  27668017.0
2010-02-05  212576350.0  11027086.0        NaN   80960063.0  20713744.0
2010-02-08  119567119.0   9898391.0        NaN   52826474.0  19856359.0
2010-02-09  158221028.0   9227158.0        NaN   59195742.0  16716845.0
2010-02-10   92590218.0   6236250.0        NaN   48591246.0  36518008.0
2010-02-11  137585903.0   8344469.0        NaN   65995913.0  24510127.0
2010-02-12  163866906.0   8075533.0        NaN   81121515.0  18929239.0
2010-02-16  135987761.0   8938494.0        NaN   51938098.0  21453147.0
...                 ...         ...        ...          ...         ...
2016-08-05   40553402.0   2704391.0  1801205.0   29335221.0   9127094.0
2016-08-08   28037220.0   1986272.0  1107857.0   19473499.0  10131279.0
2016-08-09   26315204.0   1876091.0  1318894.0   16920721.0   5971530.0
2016-08-10   24008505.0   1604280.0   786363.0   15756913.0  12981568.0
2016-08-11   27484506.0   2019740.0   975113.0   18162301.0  23938864.0
2016-08-12   18660434.0   1563318.0   740498.0   21655161.0  25182851.0
2016-08-15   25868209.0   2118521.0   938186.0   19283902.0  14441784.0
2016-08-16   33794448.0   1604561.0  1028047.0   20523493.0  13793794.0
2016-08-17   25355976.0   1891116.0   924226.0   18856423.0   8571927.0
2016-08-18   21984703.0   1458834.0   719429.0   14214341.0  11294419.0
2016-08-19   25368072.0   2343237.0   861546.0   17271044.0   9460753.0
2016-08-22   25820230.0   1679251.0   951362.0   15221922.0   6229402.0
2016-08-23   21257669.0   1524131.0   928232.0   18732373.0   8963786.0
2016-08-24   23675081.0   1744107.0  1071999.0   18151506.0   6930295.0
2016-08-25   25086248.0   1622992.0   926883.0   18552579.0   5360912.0
2016-08-26   27766291.0   2776830.0  1166681.0   20971202.0   6327991.0
2016-08-29   24970300.0   2198560.0   847565.0   16417207.0   4555600.0
2016-08-30   24863945.0   1709158.0  1130029.0   16930185.0   5804080.0
2016-08-31   29662406.0   1633789.0  1248556.0   20860269.0   7715941.0
2016-09-01   26701523.0   1792271.0   925131.0   26075363.0   5575305.0
2016-09-02   26334858.0   2157422.0  1072658.0   18900489.0   7334914.0
2016-09-06   26880391.0   3719788.0  1442822.0   16278416.0  18125776.0
2016-09-07   42364328.0   2424622.0   894021.0   17493359.0   9109446.0
2016-09-08   53002026.0   2030511.0  1270264.0   20146083.0   7882609.0
2016-09-09   46556984.0   4257344.0  1885496.0   35113934.0  12060737.0
2016-09-12   45292770.0   3124704.0  1310986.0   29302962.0  10808806.0
2016-09-13   62176190.0   3117224.0  1395046.0   30130213.0  10132044.0
2016-09-14  112340318.0   2531822.0  1094490.0   24274273.0  11625287.0
2016-09-15   90613177.0   3043534.0  1346751.0   27062614.0  12535634.0
2016-09-16   79886911.0   5499182.0  2049338.0   44606965.0  19093930.0

[1688 rows x 5 columns]

## Extracting with the `.loc[]`, `.iloc[]`, and `.ix[]` Methods

In [47]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [48]:
p.items

Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [52]:
p.loc["Low", "2014-04-08", "GOOG"]

541.61000000000001

In [55]:
p.iloc[3, 200, 3]

25.309999999999999

In [59]:
p.ix["High", 500, 4]

16.050000000000001

## Convert `Panel` to a `MultiIndex DataFrame` (and Vice Versa)

In [66]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [68]:
df = p.to_frame()
df.head()

                    Open    High     Low   Close       Volume
Date       minor
2010-01-04 AAPL    30.49   30.64   30.34   30.57  123432050.0
           AMZN   136.25  136.61  133.14  133.90    7600543.0
           MSFT    30.62   31.10   30.59   30.95   38414185.0
           YHOO    16.94   17.20   16.88   17.10   16588957.0
2010-01-05 AAPL    30.66   30.80   30.46   30.63  150476004.0

In [70]:
p2 = df.to_panel()
p2

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

## The `.major_xs()` Method

In [82]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [84]:
p.items
p["Volume"]

                   AAPL        AMZN       GOOG         MSFT        YHOO
Date
2010-01-04  123432050.0   7600543.0        NaN   38414185.0  16588957.0
2010-01-05  150476004.0   8856456.0        NaN   49758862.0  11718126.0
2010-01-06  138039594.0   7180977.0        NaN   58182332.0  16421960.0
2010-01-07  119282324.0  11030124.0        NaN   50564285.0  31816301.0
2010-01-08  111969081.0   9833829.0        NaN   51201289.0  15471074.0
2010-01-11  115557365.0   8786668.0        NaN   68754648.0  16185267.0
2010-01-12  148614774.0   9098190.0        NaN   65913228.0  15674461.0
2010-01-13  151472335.0  10727856.0        NaN   51863463.0  16961731.0
2010-01-14  108288411.0   9788435.0        NaN   63244767.0  16717061.0
2010-01-15  148584065.0  15382763.0        NaN   79915648.0  18415868.0
2010-01-19  182501620.0   8900116.0        NaN   46582886.0  15182984.0
2010-01-20  153037892.0   9081533.0        NaN   54857712.0  14421141.0
2010-01-21  152038565.0   9976146.0        NaN   73086701.0  21860505.0
2010-01-22  220441872.0  11577818.0        NaN  102004573.0  25135493.0
2010-01-25  266424802.0  12031053.0        NaN   63381173.0  19683693.0
2010-01-26  466777486.0   9567607.0        NaN   66647676.0  43979302.0
2010-01-27  430642030.0  14765273.0        NaN   63949492.0  41700911.0
2010-01-28  293375376.0  27293062.0        NaN  117513692.0  30159437.0
2010-01-29  311487785.0  29478976.0        NaN  193888424.0  39667312.0
2010-02-01  187468421.0  37774317.0        NaN   85931099.0  29865661.0
2010-02-02  174585313.0  23084986.0        NaN   54413654.0  27556624.0
2010-02-03  153831769.0  12409012.0        NaN   61397848.0  24730564.0
2010-02-04  189412762.0  12783912.0        NaN   77849968.0  27668017.0
2010-02-05  212576350.0  11027086.0        NaN   80960063.0  20713744.0
2010-02-08  119567119.0   9898391.0        NaN   52826474.0  19856359.0
2010-02-09  158221028.0   9227158.0        NaN   59195742.0  16716845.0
2010-02-10   92590218.0   6236250.0        NaN   48591246.0  36518008.0
2010-02-11  137585903.0   8344469.0        NaN   65995913.0  24510127.0
2010-02-12  163866906.0   8075533.0        NaN   81121515.0  18929239.0
2010-02-16  135987761.0   8938494.0        NaN   51938098.0  21453147.0
...                 ...         ...        ...          ...         ...
2016-08-05   40553402.0   2704391.0  1801205.0   29335221.0   9127094.0
2016-08-08   28037220.0   1986272.0  1107857.0   19473499.0  10131279.0
2016-08-09   26315204.0   1876091.0  1318894.0   16920721.0   5971530.0
2016-08-10   24008505.0   1604280.0   786363.0   15756913.0  12981568.0
2016-08-11   27484506.0   2019740.0   975113.0   18162301.0  23938864.0
2016-08-12   18660434.0   1563318.0   740498.0   21655161.0  25182851.0
2016-08-15   25868209.0   2118521.0   938186.0   19283902.0  14441784.0
2016-08-16   33794448.0   1604561.0  1028047.0   20523493.0  13793794.0
2016-08-17   25355976.0   1891116.0   924226.0   18856423.0   8571927.0
2016-08-18   21984703.0   1458834.0   719429.0   14214341.0  11294419.0
2016-08-19   25368072.0   2343237.0   861546.0   17271044.0   9460753.0
2016-08-22   25820230.0   1679251.0   951362.0   15221922.0   6229402.0
2016-08-23   21257669.0   1524131.0   928232.0   18732373.0   8963786.0
2016-08-24   23675081.0   1744107.0  1071999.0   18151506.0   6930295.0
2016-08-25   25086248.0   1622992.0   926883.0   18552579.0   5360912.0
2016-08-26   27766291.0   2776830.0  1166681.0   20971202.0   6327991.0
2016-08-29   24970300.0   2198560.0   847565.0   16417207.0   4555600.0
2016-08-30   24863945.0   1709158.0  1130029.0   16930185.0   5804080.0
2016-08-31   29662406.0   1633789.0  1248556.0   20860269.0   7715941.0
2016-09-01   26701523.0   1792271.0   925131.0   26075363.0   5575305.0
2016-09-02   26334858.0   2157422.0  1072658.0   18900489.0   7334914.0
2016-09-06   26880391.0   3719788.0  1442822.0   16278416.0  18125776.0
2016-09-07   42364328.0   2424622.0   894021.0   17493359.0   9109446.0
2016-09-08   53002026.0   2030511.0  1270264.0   20146083.0   7882609.0
2016-09-09   46556984.0   4257344.0  1885496.0   35113934.0  12060737.0
2016-09-12   45292770.0   3124704.0  1310986.0   29302962.0  10808806.0
2016-09-13   62176190.0   3117224.0  1395046.0   30130213.0  10132044.0
2016-09-14  112340318.0   2531822.0  1094490.0   24274273.0  11625287.0
2016-09-15   90613177.0   3043534.0  1346751.0   27062614.0  12535634.0
2016-09-16   79886911.0   5499182.0  2049338.0   44606965.0  19093930.0

[1688 rows x 5 columns]

In [85]:
p.major_axis

DatetimeIndex(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
               '2010-01-08', '2010-01-11', '2010-01-12', '2010-01-13',
               '2010-01-14', '2010-01-15',
               ...
               '2016-09-02', '2016-09-06', '2016-09-07', '2016-09-08',
               '2016-09-09', '2016-09-12', '2016-09-13', '2016-09-14',
               '2016-09-15', '2016-09-16'],
              dtype='datetime64[ns]', name='Date', length=1688, freq=None)

In [88]:
p.major_xs("2013-12-20")

        Open    High     Low   Close       Volume
AAPL   77.91   78.80   77.83   78.43  109103435.0
AMZN  396.84  404.72  395.78  402.20    5038537.0
GOOG  544.10  550.03  543.46  549.76          NaN
MSFT   36.25   36.93   36.18   36.80   62650324.0
YHOO   40.35   40.60   40.11   40.12   24640437.0

## The `.minor_xs()` Method

In [89]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [90]:
p.minor_axis

Index(['AAPL', 'AMZN', 'GOOG', 'MSFT', 'YHOO'], dtype='object')

In [95]:
p.minor_xs("MSFT")
p.minor_xs("GOOG").head(3)

              Open    High     Low   Close  Volume
Date
2010-01-04  313.16  314.44  311.81  313.06     NaN
2010-01-05  313.28  313.61  310.46  311.68     NaN
2010-01-06  312.62  312.62  302.88  303.83     NaN

In [96]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [102]:
p.items
p.major_axis
p.minor_axis

Index(['AAPL', 'AMZN', 'GOOG', 'MSFT', 'YHOO'], dtype='object')

In [99]:
p["Open"]
p.major_xs("2016-09-16")
p.minor_xs("YHOO")

             Open   High    Low  Close      Volume
Date
2010-01-04  16.94  17.20  16.88  17.10  16588957.0
2010-01-05  17.22  17.23  17.00  17.23  11718126.0
2010-01-06  17.17  17.30  17.07  17.17  16421960.0
2010-01-07  16.81  16.90  16.57  16.70  31816301.0
2010-01-08  16.68  16.76  16.62  16.70  15471074.0
2010-01-11  16.77  16.83  16.48  16.74  16185267.0
2010-01-12  16.65  16.86  16.60  16.68  15674461.0
2010-01-13  16.88  16.98  16.65  16.90  16961731.0
2010-01-14  16.81  17.23  16.80  17.12  16717061.0
2010-01-15  17.25  17.25  16.75  16.82  18415868.0
2010-01-19  16.78  16.96  16.64  16.75  15182984.0
2010-01-20  16.65  16.68  16.25  16.38  14421141.0
2010-01-21  16.39  16.58  16.10  16.20  21860505.0
2010-01-22  16.08  16.21  15.81  15.88  25135493.0
2010-01-25  16.07  16.11  15.74  15.86  19683693.0
2010-01-26  15.82  16.17  15.70  15.99  43979302.0
2010-01-27  16.46  16.49  15.77  15.98  41700911.0
2010-01-28  15.93  15.96  15.44  15.44  30159437.0
2010-01-29  15.51  15.67  14.90  15.01  39667312.0
2010-02-01  15.14  15.30  14.87  15.05  29865661.0
2010-02-02  15.10  15.32  15.03  15.17  27556624.0
2010-02-03  15.12  15.60  15.12  15.46  24730564.0
2010-02-04  15.34  15.52  14.99  15.01  27668017.0
2010-02-05  15.01  15.25  14.92  15.19  20713744.0
2010-02-08  15.18  15.47  14.95  14.99  19856359.0
2010-02-09  15.20  15.24  14.94  15.07  16716845.0
2010-02-10  15.02  15.02  14.48  14.80  36518008.0
2010-02-11  14.87  15.25  14.76  15.22  24510127.0
2010-02-12  15.07  15.19  14.85  15.17  18929239.0
2010-02-16  15.23  15.48  15.18  15.41  21453147.0
...           ...    ...    ...    ...         ...
2016-08-05  39.00  39.15  38.90  38.99   9127094.0
2016-08-08  39.00  39.27  38.86  39.24  10131279.0
2016-08-09  39.24  39.31  39.10  39.24   5971530.0
2016-08-10  39.34  39.98  39.30  39.93  12981568.0
2016-08-11  41.12  41.73  40.93  41.27  23938864.0
2016-08-12  41.28  42.98  41.28  42.94  25182851.0
2016-08-15  43.18  43.29  42.43  42.67  14441784.0
2016-08-16  42.30  42.79  41.95  42.49  13793794.0
2016-08-17  42.39  42.75  42.39  42.70   8571927.0
2016-08-18  42.69  42.97  42.58  42.90  11294419.0
2016-08-19  42.80  43.12  42.64  43.02   9460753.0
2016-08-22  42.84  42.87  42.33  42.52   6229402.0
2016-08-23  42.61  42.91  42.45  42.60   8963786.0
2016-08-24  42.50  42.77  41.79  41.91   6930295.0
2016-08-25  41.83  42.24  41.73  42.03   5360912.0
2016-08-26  42.15  42.61  41.94  42.27   6327991.0
2016-08-29  42.20  42.46  42.08  42.26   4555600.0
2016-08-30  42.28  42.74  42.28  42.58   5804080.0
2016-08-31  42.46  42.80  42.46  42.75   7715941.0
2016-09-01  42.78  43.10  42.72  42.93   5575305.0
2016-09-02  43.27  43.60  43.08  43.28   7334914.0
2016-09-06  43.50  44.85  43.50  44.71  18125776.0
2016-09-07  44.55  44.92  44.19  44.35   9109446.0
2016-09-08  44.07  44.72  44.03  44.36   7882609.0
2016-09-09  43.92  44.15  42.82  42.92  12060737.0
2016-09-12  42.28  43.65  42.18  43.46  10808806.0
2016-09-13  43.19  43.52  42.69  43.04  10132044.0
2016-09-14  42.91  43.62  42.86  43.46  11625287.0
2016-09-15  43.41  44.05  43.22  43.99  12535634.0
2016-09-16  43.94  44.02  43.47  43.67  19093930.0

[1688 rows x 5 columns]

## Transpose a `Panel` with the `.transpose()` Method

In [12]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1713 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-10-21 00:00:00
Minor_axis axis: AAPL to YHOO

In [13]:
p.axes

[Index([u'Open', u'High', u'Low', u'Close', u'Volume'], dtype='object'),
 DatetimeIndex(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
                '2010-01-08', '2010-01-11', '2010-01-12', '2010-01-13',
                '2010-01-14', '2010-01-15',
                ...
                '2016-10-10', '2016-10-11', '2016-10-12', '2016-10-13',
                '2016-10-14', '2016-10-17', '2016-10-18', '2016-10-19',
                '2016-10-20', '2016-10-21'],
               dtype='datetime64[ns]', name=u'Date', length=1713, freq=None),
 Index([u'AAPL', u'AMZN', u'GOOG', u'MSFT', u'YHOO'], dtype='object')]

In [15]:
p2 = p.transpose(2, 1, 0)

In [16]:
p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1713 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-10-21 00:00:00
Minor_axis axis: AAPL to YHOO

In [19]:
p2["GOOG"]

              Open    High     Low   Close     Volume
Date
2010-01-04  313.16  314.44  311.81  313.06        NaN
2010-01-05  313.28  313.61  310.46  311.68        NaN
2010-01-06  312.62  312.62  302.88  303.83        NaN
2010-01-07  304.40  304.70  296.03  296.75        NaN
2010-01-08  295.70  301.32  294.26  300.71        NaN
2010-01-11  301.93  301.93  296.72  300.25        NaN
2010-01-12  298.74  298.78  293.71  294.94        NaN
2010-01-13  287.96  293.90  286.66  293.25        NaN
2010-01-14  291.66  296.80  291.11  294.63        NaN
2010-01-15  295.50  296.48  288.73  289.71        NaN
2010-01-19  290.45  294.91  287.86  293.52        NaN
2010-01-20  292.70  292.70  287.36  289.91        NaN
2010-01-21  291.43  293.12  285.84  291.20        NaN
2010-01-22  281.97  285.01  267.16  274.73        NaN
2010-01-25  273.02  274.66  267.49  269.73        NaN
2010-01-26  268.72  274.53  267.88  270.94        NaN
2010-01-27  270.36  273.55  267.39  270.78        NaN
2010-01-28  271.97  273.23  265.03  266.88        NaN
2010-01-29  268.98  270.22  262.54  264.71        NaN
2010-02-01  267.03  267.64  264.88  266.24        NaN
2010-02-02  267.21  267.21  263.54  265.29        NaN
2010-02-03  264.07  270.78  263.85  270.14        NaN
2010-02-04  268.23  268.73  262.52  263.13        NaN
2010-02-05  263.94  266.48  260.97  265.38        NaN
2010-02-08  265.98  270.73  265.50  266.47        NaN
2010-02-09  269.50  270.49  267.27  267.95        NaN
2010-02-10  266.77  268.63  263.58  266.96        NaN
2010-02-11  265.86  269.97  264.49  267.93        NaN
2010-02-12  266.22  268.31  264.98  266.29        NaN
2010-02-16  268.30  271.79  266.88  270.38        NaN
...            ...     ...     ...     ...        ...
2016-09-12  755.13  770.29  754.00  769.02  1310986.0
2016-09-13  764.48  766.22  755.80  759.69  1395046.0
2016-09-14  759.61  767.68  759.11  762.49  1094490.0
2016-09-15  762.89  773.80  759.96  771.76  1346751.0
2016-09-16  769.75  769.75  764.66  768.88  2049338.0
2016-09-19  772.42  774.00  764.44  765.70  1172824.0
2016-09-20  769.00  773.33  768.53  771.41   978631.0
2016-09-21  772.66  777.16  768.30  776.22  1167810.0
2016-09-22  780.00  789.85  778.44  787.21  1486223.0
2016-09-23  786.59  788.93  784.15  786.90  1411937.0
2016-09-26  782.74  782.74  773.07  774.21  1533206.0
2016-09-27  775.50  785.99  774.31  783.01  1153247.0
2016-09-28  777.85  781.81  774.97  781.56  1109834.0
2016-09-29  781.44  785.80  774.23  775.01  1314746.0
2016-09-30  776.33  780.94  774.09  777.29  1585333.0
2016-10-03  774.25  776.06  769.50  772.56  1278821.0
2016-10-04  776.03  778.71  772.89  776.43  1201350.0
2016-10-05  779.31  782.07  775.65  776.47  1461151.0
2016-10-06  779.00  780.48  775.54  776.86  1070692.0
2016-10-07  779.66  779.66  770.75  775.08   933158.0
2016-10-10  777.71  789.38  775.87  785.94  1174923.0
2016-10-11  786.66  792.28  780.58  783.07  1372461.0
2016-10-12  783.76  788.13  782.06  786.14   937435.0
2016-10-13  781.22  781.22  773.00  778.19  1365277.0
2016-10-14  781.65  783.95  776.00  778.53   852487.0
2016-10-17  779.80  785.85  777.50  779.96  1092973.0
2016-10-18  787.85  801.61  785.56  795.26  2056903.0
2016-10-19  798.86  804.63  797.64  801.56  1766798.0
2016-10-20  803.30  803.97  796.03  796.97  1757528.0
2016-10-21  795.00  799.50  794.00  799.37  1266181.0

[1713 rows x 5 columns]

In [20]:
p2.major_xs("2010-01-04")

                AAPL        AMZN    GOOG         MSFT         YHOO
Open    3.049000e+01      136.25  313.16        30.62        16.94
High    3.064000e+01      136.61  314.44        31.10        17.20
Low     3.034000e+01      133.14  311.81        30.59        16.88
Close   3.057000e+01      133.90  313.06        30.95        17.10
Volume  1.234320e+08  7600543.00     NaN  38414185.00  16588957.00

In [21]:
p2.minor_xs("Volume")

                   AAPL        AMZN       GOOG         MSFT        YHOO
Date
2010-01-04  123432050.0   7600543.0        NaN   38414185.0  16588957.0
2010-01-05  150476004.0   8856456.0        NaN   49758862.0  11718126.0
2010-01-06  138039594.0   7180977.0        NaN   58182332.0  16421960.0
2010-01-07  119282324.0  11030124.0        NaN   50564285.0  31816301.0
2010-01-08  111969081.0   9833829.0        NaN   51201289.0  15471074.0
2010-01-11  115557365.0   8786668.0        NaN   68754648.0  16185267.0
2010-01-12  148614774.0   9098190.0        NaN   65913228.0  15674461.0
2010-01-13  151472335.0  10727856.0        NaN   51863463.0  16961731.0
2010-01-14  108288411.0   9788435.0        NaN   63244767.0  16717061.0
2010-01-15  148584065.0  15382763.0        NaN   79915648.0  18415868.0
2010-01-19  182501620.0   8900116.0        NaN   46582886.0  15182984.0
2010-01-20  153037892.0   9081533.0        NaN   54857712.0  14421141.0
2010-01-21  152038565.0   9976146.0        NaN   73086701.0  21860505.0
2010-01-22  220441872.0  11577818.0        NaN  102004573.0  25135493.0
2010-01-25  266424802.0  12031053.0        NaN   63381173.0  19683693.0
2010-01-26  466777486.0   9567607.0        NaN   66647676.0  43979302.0
2010-01-27  430642030.0  14765273.0        NaN   63949492.0  41700911.0
2010-01-28  293375376.0  27293062.0        NaN  117513692.0  30159437.0
2010-01-29  311487785.0  29478976.0        NaN  193888424.0  39667312.0
2010-02-01  187468421.0  37774317.0        NaN   85931099.0  29865661.0
2010-02-02  174585313.0  23084986.0        NaN   54413654.0  27556624.0
2010-02-03  153831769.0  12409012.0        NaN   61397848.0  24730564.0
2010-02-04  189412762.0  12783912.0        NaN   77849968.0  27668017.0
2010-02-05  212576350.0  11027086.0        NaN   80960063.0  20713744.0
2010-02-08  119567119.0   9898391.0        NaN   52826474.0  19856359.0
2010-02-09  158221028.0   9227158.0        NaN   59195742.0  16716845.0
2010-02-10   92590218.0   6236250.0        NaN   48591246.0  36518008.0
2010-02-11  137585903.0   8344469.0        NaN   65995913.0  24510127.0
2010-02-12  163866906.0   8075533.0        NaN   81121515.0  18929239.0
2010-02-16  135987761.0   8938494.0        NaN   51938098.0  21453147.0
...                 ...         ...        ...          ...         ...
2016-09-12   45292770.0   3124704.0  1310986.0   29302962.0  10808806.0
2016-09-13   62176190.0   3117224.0  1395046.0   30130213.0  10132044.0
2016-09-14  112340318.0   2531822.0  1094490.0   24274273.0  11625287.0
2016-09-15   90613177.0   3043534.0  1346751.0   27062614.0  12535634.0
2016-09-16   79886911.0   5499182.0  2049338.0   44606965.0  19093930.0
2016-09-19   47023046.0   2297221.0  1172824.0   20937104.0   7887375.0
2016-09-20   34514269.0   1937164.0   978631.0   17383982.0   9788923.0
2016-09-21   36003185.0   2718644.0  1167810.0   33707272.0  12313680.0
2016-09-22   31073984.0   4078910.0  1486223.0   19822203.0  33355616.0
2016-09-23   52481151.0   2353511.0  1411937.0   19955336.0  31888521.0
2016-09-26   29869442.0   2651397.0  1533206.0   21688720.0  12745119.0
2016-09-27   24607412.0   3819600.0  1153247.0   28065071.0   8765715.0
2016-09-28   29641085.0   4422078.0  1109834.0   20536400.0   7418984.0
2016-09-29   35886990.0   4922248.0  1314746.0   25463536.0  13720746.0
2016-09-30   36379106.0   4430566.0  1585333.0   29910788.0  10374757.0
2016-10-03   21701760.0   2769448.0  1278821.0   19189515.0   7965922.0
2016-10-04   29736835.0   2950314.0  1201350.0   20085874.0   8998384.0
2016-10-05   21453089.0   3469055.0  1461151.0   16726411.0   6118487.0
2016-10-06   28779313.0   2684013.0  1070692.0   16212611.0   6293908.0
2016-10-07   24358443.0   2426228.0   933158.0   20089020.0   8502112.0
2016-10-10   36235956.0   1827143.0  1174923.0   18196509.0   6573631.0
2016-10-11   64041043.0   3588180.0  1372461.0   26497418.0   9513283.0
2016-10-12   37586787.0   2380416.0   937435.0   22177464.0   7290843.0
2016-10-13   35192406.0   3091387.0  1365277.0   25313748.0  15689711.0
2016-10-14   35652191.0   2999814.0   852487.0   27402451.0   7781258.0
2016-10-17   23624896.0   3361492.0  1092973.0   23830014.0   8620369.0
2016-10-18   24553478.0   2512504.0  2056903.0   19149538.0  19360802.0
2016-10-19   20034594.0   2090706.0  1766798.0   22878397.0  14532469.0
2016-10-20   24125801.0   3151954.0  1757528.0   49455612.0  11671022.0
2016-10-21   23192665.0   2793015.0  1266181.0   80032206.0   7194168.0

[1713 rows x 5 columns]

## The `.swapaxes()` Method

In [115]:
companies = ["MSFT", "GOOG", "AAPL", "IBM", "AMZN"]

p = data.DataReader(name = companies, data_source = "yahoo", start = "2010-01-01", end = "2016-12-31")

p

<class 'pandas.core.panel.Panel'>
Dimensions: 5 (items) x 1688 (major_axis) x 5 (minor_axis)
Items axis: Open to Volume
Major_axis axis: 2010-01-04 00:00:00 to 2016-09-16 00:00:00
Minor_axis axis: AAPL to YHOO

In [117]:
p2 = p.swapaxes("items", "minor")

In [118]:
p2.axes

[Index(['AAPL', 'AMZN', 'GOOG', 'MSFT', 'YHOO'], dtype='object'),
 DatetimeIndex(['2010-01-04', '2010-01-05', '2010-01-06', '2010-01-07',
                '2010-01-08', '2010-01-11', '2010-01-12', '2010-01-13',
                '2010-01-14', '2010-01-15',
                ...
                '2016-09-02', '2016-09-06', '2016-09-07', '2016-09-08',
                '2016-09-09', '2016-09-12', '2016-09-13', '2016-09-14',
                '2016-09-15', '2016-09-16'],
               dtype='datetime64[ns]', name='Date', length=1688, freq=None),
 Index(['Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')]

In [121]:
p2["MSFT"]
p2.major_xs("2016-09-02")
p2.minor_xs("Close")

              AAPL    AMZN    GOOG   MSFT   YHOO
Date
2010-01-04   30.57  133.90  313.06  30.95  17.10
2010-01-05   30.63  134.69  311.68  30.96  17.23
2010-01-06   30.14  132.25  303.83  30.77  17.17
2010-01-07   30.08  130.00  296.75  30.45  16.70
2010-01-08   30.28  133.52  300.71  30.66  16.70
2010-01-11   30.02  130.31  300.25  30.27  16.74
2010-01-12   29.67  127.35  294.94  30.07  16.68
2010-01-13   30.09  129.11  293.25  30.35  16.90
2010-01-14   29.92  127.35  294.63  30.96  17.12
2010-01-15   29.42  127.14  289.71  30.86  16.82
2010-01-19   30.72  127.61  293.52  31.10  16.75
2010-01-20   30.25  125.78  289.91  30.58  16.38
2010-01-21   29.72  126.62  291.20  30.01  16.20
2010-01-22   28.25  121.43  274.73  28.96  15.88
2010-01-25   29.01  120.31  269.73  29.32  15.86
2010-01-26   29.42  119.48  270.94  29.50  15.99
2010-01-27   29.70  122.75  270.78  29.67  15.98
2010-01-28   28.47  126.03  266.88  29.16  15.44
2010-01-29   27.44  125.41  264.71  28.18  15.01
2010-02-01   27.82  118.87  266.24  28.41  15.05
2010-02-02   27.98  118.12  265.29  28.46  15.17
2010-02-03   28.46  119.10  270.14  28.63  15.46
2010-02-04   27.44  115.94  263.13  27.84  15.01
2010-02-05   27.92  117.39  265.38  28.02  15.19
2010-02-08   27.73  116.83  266.47  27.72  14.99
2010-02-09   28.03  118.03  267.95  28.01  15.07
2010-02-10   27.87  117.36  266.96  27.99  14.80
2010-02-11   28.38  120.09  267.93  28.12  15.22
2010-02-12   28.63  119.66  266.29  27.93  15.17
2010-02-16   29.06  117.53  270.38  28.35  15.41
...            ...     ...     ...    ...    ...
2016-08-05  107.48  765.98  782.22  57.96  38.99
2016-08-08  108.37  766.56  781.76  58.06  39.24
2016-08-09  108.81  768.31  784.26  58.20  39.24
2016-08-10  108.00  768.56  784.68  58.02  39.93
2016-08-11  107.93  771.24  784.85  58.30  41.27
2016-08-12  108.18  772.56  783.22  57.94  42.94
2016-08-15  109.48  768.49  782.44  58.12  42.67
2016-08-16  109.38  764.04  777.14  57.44  42.49
2016-08-17  109.22  764.63  779.91  57.56  42.70
2016-08-18  109.08  764.46  777.50  57.60  42.90
2016-08-19  109.36  757.31  775.42  57.62  43.02
2016-08-22  108.51  759.48  772.15  57.67  42.52
2016-08-23  108.85  762.45  772.08  57.89  42.60
2016-08-24  108.03  757.25  769.64  57.95  41.91
2016-08-25  107.57  759.22  769.41  58.17  42.03
2016-08-26  106.94  769.00  769.54  58.03  42.27
2016-08-29  106.82  771.29  772.15  58.10  42.26
2016-08-30  106.00  767.58  769.09  57.89  42.58
2016-08-31  106.10  769.16  767.05  57.46  42.75
2016-09-01  106.73  770.62  768.78  57.59  42.93
2016-09-02  107.73  772.44  771.46  57.67  43.28
2016-09-06  107.70  788.87  780.08  57.61  44.71
2016-09-07  108.36  784.48  780.35  57.66  44.35
2016-09-08  105.52  784.06  775.32  57.43  44.36
2016-09-09  103.13  760.14  759.66  56.21  42.92
2016-09-12  105.44  771.49  769.02  57.05  43.46
2016-09-13  107.95  761.01  759.69  56.53  43.04
2016-09-14  111.77  761.09  762.49  56.26  43.46
2016-09-15  115.57  769.69  771.76  57.19  43.99
2016-09-16  114.92  778.52  768.88  57.25  43.67

[1688 rows x 5 columns]